### ISSUE TITLE
when running the command: python demo.py --gpu 0 --stage param --test_epoch 8 I get the following error, can someone help me please to solve it

### ISSUE THREAD

**Issue by MhmdAliChamass99** [mks0601/I2L-MeshNet_RELEASE#104]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\OpenGL\platform\egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "C:\Python39\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Desktop\5th year- 1st semester\FYP\I2L-MeshNet_RELEASE-master\demo\demo.py", line 19, in <module>
    from utils.vis import vis_mesh, save_obj, render_mesh
  File "C:\Users\USER\OneDrive\Desktop\5th year- 1st semester\FYP\I2L-MeshNet_RELEASE-master\main\..\common\utils\vis.py", line 8, in <module>
    import pyrender
  File "C:\Python39\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "C:\Python39\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "C:\Python39\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Python39\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Python39\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Python39\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Python39\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Python39\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

C:\Users\USER\OneDrive\Desktop\5th year- 1st semester\FYP\I2L-MeshNet_RELEASE-master\demo>python demo.py --gpu 0 --stage param --test_epoch 8
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\OpenGL\platform\egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "C:\Python39\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: ("Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Desktop\5th year- 1st semester\FYP\I2L-MeshNet_RELEASE-master\demo\demo.py", line 19, in <module>
    from utils.vis import vis_mesh, save_obj, render_mesh
  File "C:\Users\USER\OneDrive\Desktop\5th year- 1st semester\FYP\I2L-MeshNet_RELEASE-master\main\..\common\utils\vis.py", line 8, in <module>
    import pyrender
  File "C:\Python39\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "C:\Python39\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "C:\Python39\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Python39\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Python39\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Python39\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Python39\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Python39\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

**Comment by mks0601** [comment]
Try comment out this: https://github.com/mks0601/I2L-MeshNet_RELEASE/blob/4c71b89713eccfb893607963696f368f4beb9fa6/common/utils/vis.py#L7

**Comment by MhmdAliChamass99** [comment]
Thank you so much, it worked out but another error appears telling me that
Torch not compiled with CUDA enabled, any thoughts on this please?

**Comment by mks0601** [comment]
Please re-install Torch with CUDA.

**Comment by MhmdAliChamass99** [comment]
I really appreciate it, thank you!!

Do you mind me reaching you in case I face any more issues?

**Comment by mks0601** [comment]
Sure, but please google the errors before asking me. Thanks!

**Comment by MhmdAliChamass99** [comment]
Yes the one related to the Egl environment i googled it and it consumed so
much of my time as i was commenting the ones found in offscreen.py. Thank
you anyway!
