### ISSUE TITLE
help for sizemismatch problem

### ISSUE THREAD

**Issue by vrf-xcugas** [mks0601/I2L-MeshNet_RELEASE#115]
>>> Using GPU: 0
Load checkpoint from ./snapshot_7.pth.tar
Traceback (most recent call last):
  File "demo/demo.py", line 75, in <module>
    model.load_state_dict(ckpt['network'], strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.human_model_layer.th_betas: copying a param with shape torch.Size([1, 10]) from checkpoint, the shape in current model is torch.Size([1, 300]).
	size mismatch for module.human_model_layer.th_shapedirs: copying a param with shape torch.Size([6890, 3, 10]) from checkpoint, the shape in current model is torch.Size([6890, 3, 300]).

**Comment by sree181** [comment]
You are useing the wrong checkpoint file  for example you are  using  basicModel_f_lbs_10_207_0_v1.1.0.pkl  instead please use basicModel_f_lbs_10_207_0_v1.0.0.pkl, do same  for male and  Neutral

**Comment by baboonaaaa** [comment]
hello,have you resolved this problem?
