### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Josef4Sci** [mks0601/I2L-MeshNet_RELEASE#12]
**Got this exeption after running _python demo.py --gpu 0 --stage param --test_epoch 8_:**
Traceback (most recent call last):
  File "demo.py", line 72, in <module>
    ckpt = torch.load(model_path)
  File "/home/justjo/miniconda2/envs/I2L_meshNET/lib/python3.8/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/justjo/miniconda2/envs/I2L_meshNET/lib/python3.8/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

Pytorch 1.6, Python tested both 3.7.3 and 3.8.5.

**Comment by mks0601** [comment]
I haven't met this error. Could you download the model again? https://github.com/CSAILVision/places365/issues/49
