### ISSUE TITLE
Demo: Library "GLU" not found.

### ISSUE THREAD

**Issue by zhaoyuanyuan2011** [mks0601/I2L-MeshNet_RELEASE#21]
Has anyone had this error when trying to run demo?

Traceback (most recent call last):
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/__init__.py", line 334, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/__init__.py", line 334, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute '_create_shadow_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    from utils.vis import vis_mesh, save_obj, render_mesh
  File "/home/yzhao/yzhao/I2L-MeshNet_RELEASE/main/../common/utils/vis.py", line 7, in <module>
    import pyrender
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyrender/__init__.py", line 12, in <module>
    from .viewer import Viewer
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyrender/viewer.py", line 36, in <module>
    class Viewer(pyglet.window.Window):
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/__init__.py", line 340, in __getattr__
    __import__(import_name)
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/window/__init__.py", line 1897, in <module>
    gl._create_shadow_window()
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/__init__.py", line 340, in __getattr__
    __import__(import_name)
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/yzhao/anaconda3/envs/i2l/lib/python3.8/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

Tested with both python3.7 and python3.8.

**Comment by mks0601** [comment]
Could you try on your local machine, not using ssh? The renderer needs a display device.

**Comment by zhaoyuanyuan2011** [comment]
> Could you try on your local machine, not using ssh? The renderer needs a display device.

Thank you for the quick reply! Since I don't have a GPU on my local machine, does that mean I cannot run this demo at all in this case?

**Comment by mks0601** [comment]
Ithink you can switch off the rendering in the demo code? Or google how to use renderer in ssh?

**Comment by zhaoyuanyuan2011** [comment]
Thank you for the suggestions! I finally figured out that rendering over ssh can be finished using EGL.

**Comment by mks0601** [comment]
Good for you!

**Comment by zqq-judy** [comment]
@mks0601 @zhaoyuanyuan2011 

1. When I run demo.py, an error occurs：
   
![image](https://user-images.githubusercontent.com/40655640/96325433-33f92880-105a-11eb-8592-1c589b547b77.png)

2. I added this at the top of my script (demo.py):
`import os
os.environ['PYOPENGL_PLATFORM']='egl'`

But, I get mistakes, as follows:
![image](https://user-images.githubusercontent.com/40655640/96325435-3b203680-105a-11eb-8c29-9591b9d3aec8.png)

I tried google to search for a solution, but it didn't solve it. Can I get some help from you? 
The environment is ubuntu16.04 and python3.7.  ( I don't have a GPU on my local machine.)
Thanks!

**Comment by mks0601** [comment]
Are you running the code on ssh? The rendering requires some display device, so you'd better run the demo code on your local machine. Or you can disable the rendering part and run the code on ssh.

**Comment by Hasankanso** [comment]
> I think you can switch off the rendering in the demo code? Or google how to use renderer in ssh?

the current version of  I2L_MeshNet's demo.py already uses offscreen in vis.py:

```
def render_mesh(img, mesh, face, cam_param):
    ...
    renderer = pyrender.OffscreenRenderer(viewport_width=img.shape[1], viewport_height=img.shape[0], point_size=1.0)
    ...
    return img
```
I'm having the same issues as @zqq-judy I injected this line `os.environ['PYOPENGL_PLATFORM']='egl'` and got same results as him

Unfortunately I don't understand the problem to know what should I do. I'm trying to run it inside of a docker container, should I install a specific version of pyrender (older one?). I need it running inside of docker.

any suggestions for a workaround?
