### ISSUE TITLE
There are some errors about  multi-GPUs

### ISSUE THREAD

**Issue by sunjc0306** [mks0601/I2L-MeshNet_RELEASE#29]
The following error occurs whatever the 'gpu_ids' is setten '0' or '0-1' in 'demo.py' file.
However, there will be no error if 'model = DataParallel(model).cuda()' is removed and updated model = model.cuda()
It seems that this program can not implemented for multi-GPUs .
`>>> Using GPU: 0,1
Load checkpoint from ../snapshot_8.pth.tar
Traceback (most recent call last):
  File "/home/sunjc0306/sunjc0306/I2L-MeshNet_RELEASE/demo/demo.py", line 93, in <module>
    out = model(inputs, targets, meta_info, 'test')
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    for k in out))
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in <genexpr>
    for k in out))
  File "/home/sunjc0306/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: expected sequence object with len >= 0 or a single integer`

**Comment by mks0601** [comment]
Hmm.. I haven't check the demo code using multi-gpus. If you met error, I think the reason is that the model expects images of more than the number of gpus, but there is only one image.

**Comment by pursur** [comment]
There is  a lines for  'nn.DataParallel' In your demo  code.
Is not this used for multi-gpus?

**Comment by pursur** [comment]
There is  a line for  'nn.DataParallel' in your demo  code.
Is not this used for multi-gpus?

**Comment by mks0601** [comment]
If you run demo by `--gpu 0`,  then the code will use only one gpu
