### ISSUE TITLE
ImportError: ('Unable to load EGL library', 22, 'The specified module could not be found', None, 126, None, 'EGL', None)

### ISSUE THREAD

**Issue by its-charan-here** [mks0601/I2L-MeshNet_RELEASE#97]
**I am facing this error while running the code. Can someone help me to resolve this issue?**

`ImportError: ('Unable to load EGL library', 22, 'The specified module could not be found', None, 126, None, 'EGL', None)`

Terminal :
```

Traceback (most recent call last):
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\detect_3d_vid.py", line 30, in <module>
    from i2l_mesh.demo.demo_yolo_video import mesh_3d
  File "E:\i2l_mesh\demo\demo_yolo_video.py", line 19, in <module>
    from i2l_mesh.common.utils.vis import vis_mesh, save_obj, render_mesh
  File "E:\i2l_mesh\common\utils\vis.py", line 8, in <module>
    import pyrender
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\pyrender\light.py", line 10, in <module>
    from OpenGL.GL import *
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\Vignesh\anaconda3\envs\mesh\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 22, 'The specified module could not be found', None, 126, None, 'EGL', None)
```

**Comment by MhmdAliChamass99** [comment]
@its-charan-here did you solve it?
If yes, please share the answer because I am facing the same problem

**Comment by nwicakson** [comment]
@its-charan-here @MhmdAliChamass99 Hello, I'm facing this same problem. If you solved this problem, could you please share the answer? Thanks
